import { getEnvSafely } from './config';

/**
 * For server-used only
 */
const MONGODB_URI = getEnvSafely('MONGODB_URI');
const NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = getEnvSafely('NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY');
const CLERK_SECRET_KEY = getEnvSafely('CLERK_SECRET_KEY');
const CLERK_WEBHOOK_SECRET = getEnvSafely('CLERK_WEBHOOK_SECRET');
const NEXT_PUBLIC_CLERK_SIGN_IN_URL = getEnvSafely('NEXT_PUBLIC_CLERK_SIGN_IN_URL');
const NEXT_PUBLIC_CLERK_SIGN_UP_URL = getEnvSafely('NEXT_PUBLIC_CLERK_SIGN_UP_URL');
const NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL = getEnvSafely('NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL');
const NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL = getEnvSafely('NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL');
const NODE_ENV = getEnvSafely('NODE_ENV'); // Assuming NODE_ENV is used to determine environment mode
const NEXTAUTH_SECRET = getEnvSafely('NEXTAUTH_SECRET');

const env = {
  MONGODB_URI,
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  CLERK_SECRET_KEY,
  CLERK_WEBHOOK_SECRET,
  NEXT_PUBLIC_CLERK_SIGN_IN_URL,
  NEXT_PUBLIC_CLERK_SIGN_UP_URL,
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL,
  NODE_ENV,
  NEXTAUTH_SECRET,
};

export default env;
